### PR TITLE
Add assert_between

### PR DESCRIPTION
**Pull request by jaggederest**
Add an 'assert_between' method to match similar functionality in Test::Unit::Assertions

### CODE REVIEW

**Comment by bensomers** [comment]
Do you have a reference to where this method is defined in Test::Unit? Not strictly necessary, but in cases where we explicitly want to mimic Test::Unit it's useful.

I'll probably go ahead and merge this anyway; minitest-extra-assertions is probably best used as a grab bag for more assertion methods, so being permissive is what makes sense.

**Comment by jaggederest** [comment]
Well, I retract my statement that there's similar functionality. I guess I was thinking of assert_include, which is slightly different in nature, just calling obj.include?(exp)

assert_include doesn't work for my usual case, which is assert_between(start_time, end_time, time_in_question, "should have happened between #{start_time} and #{end_time}"), since ranges with time don't compare smoothly.

Thanks for the quick response.

**Comment by bensomers** [comment]
I'll look over this later today or tomorrow, and release a new version if it looks good (which I expect it will).

**Comment by bensomers** [comment]
All right, I've pulled in your assertion and added you to the (newly-created) contributors list. New release forthcoming.

And I think "this":http://rhnh.net/2009/08/03/range-include-in-ruby-1-9 may have been the behavior you were thinking of; in the old 1.8 implementation, I think assert_include would've given you what you're looking for.

**Pull request closed without merging**
